[theme]
# Cor principal (Botões, sliders, links) - Um roxo vibrante
primaryColor = "#6C63FF"

# Cor de fundo da área principal - Cinza bem escuro
backgroundColor = "#0E1117"

# Cor de fundo da barra lateral - Um pouco mais claro que o fundo
secondaryBackgroundColor = "#262730"

# Cor do texto - Quase branco para dar contraste
textColor = "#FAFAFA"

# Fonte (opções: "sans serif", "serif", "monospace")
font = "sans serif"