[connections.supabase]
dialect = "postgresql"
host = "postgresql://postgres:G3c8WJ2JdzRLCok5@db.nbfvljhwnexszcfxovos.supabase.co:5432/postgres" # Pegue do seu link URI
port = "5432"
database = "postgres"
username = "postgres"
password = "G3c8WJ2JdzRLCok5"
